spring:
  application:
    name: JavaTest
  h2:
    console.enabled: true
    console.path: /h2-console
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:movieDB;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8020
  servlet:
    context-path: /api






